package com.example.demo.mapper;

import com.example.demo.entity.LearnResource;

import java.util.List;
import java.util.Map;

public interface LearnResourceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table learn_resource
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table learn_resource
     *
     * @mbggenerated
     */
    int insert(LearnResource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table learn_resource
     *
     * @mbggenerated
     */
    int insertSelective(LearnResource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table learn_resource
     *
     * @mbggenerated
     */
    LearnResource selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table learn_resource
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(LearnResource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table learn_resource
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(LearnResource record);

    List<LearnResource> queryLearnResouceList(Map<String, Object> params);
}